-- Database per Gestione presenze
-- Incolla tutto questo script in Supabase > SQL Editor e premi Run.

create table if not exists public.orari (
  id bigint generated by default as identity primary key,
  employee text not null check (employee in ('Donnarumma','Labartino','Serrentino','Volza')),
  date date not null,
  type text not null check (type in ('lavoro','permesso','ferie')),
  start_time text,
  end_time text,
  minutes integer not null default 0,
  status text,
  created_at timestamptz not null default now(),
  unique(employee, date, type)
);

alter table public.orari enable row level security;

-- I colleghi possono inserire i propri dati dalla pagina pubblica.
drop policy if exists "orari_insert_anon" on public.orari;
create policy "orari_insert_anon"
on public.orari for insert
to anon, authenticated
with check (true);

-- Nessuna lettura pubblica: il riepilogo deve usare un account autenticato.
drop policy if exists "orari_select_authenticated" on public.orari;
create policy "orari_select_authenticated"
on public.orari for select
to authenticated
using (true);

-- Aggiornamenti autenticati (utile per correggere una registrazione).
drop policy if exists "orari_update_authenticated" on public.orari;
create policy "orari_update_authenticated"
on public.orari for update
to authenticated
using (true)
with check (true);

-- Cancellazione solo per utenti autenticati. La pagina riepilogo la abilita con una conferma.
drop policy if exists "orari_delete_authenticated" on public.orari;
create policy "orari_delete_authenticated"
on public.orari for delete
to authenticated
using (true);
